
# This is the class for the result generated by the SegmentAndFit function
# Verify with Stefan that this doesn't need a validator and a helper
# because construction of the class shouldn't be accessible to users

# Constructor
new_HistogramFit = function(models, p){
  stopifnot(is.list(models))
  stopifnot(is.integer(p))

  structure(
    models,
    p = p,
    class = "HistogramFit"
  )
}
