on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    container:
      image: stefaneng/consensuspeaks:latest

    steps:
      - uses: actions/checkout@v2
           with:
             path: ConsensusPeaks
      - run: R CMD build --compact-vignettes="gs+qpdf" ConsensusPeaks
      - run: R CMD check --as-cran --run-donttest ConsensusPeaks_*.tar.gz
