---
name: R-CMD-check

on:
   - push
   - pull_request

jobs:
   R-CMD-check:
      runs-on: ubuntu-latest

      container:
         image: blcdsdockerregistry/bl-r-devel:latest

      steps:
         - uses: actions/checkout@v2
           with:
              path: BoutrosLabTemplate
         - run: R CMD build --compact-vignettes="gs+qpdf" ConsensusPeaks
         - run: R CMD check --as-cran ConsensusPeaks_*.tar.gz
